### ISSUE TITLE
Variable Delete

### ISSUE THREAD

**Issue by florianika** [parstat/iais-frontend#106]
- [x] Create the delete method in the variable service
- [x] Create the delete method in the variable store
- [x] Create the delete view in the variable views (In variable list add delete action)
The delete view should contain this fields:
1. LocalId
2. Name
3. Description
4. Definition
5. List of representation in a table (check variable view)
6. Delete button that should delete the dispatch the delete method from the store, on success redirect to variable list view

**Comment by ReiPano** [comment]
Not tested yet
