### ISSUE TITLE
Create Unit Dataset

### ISSUE THREAD

**Issue by florianika** [parstat/iais-frontend#112]
- [x] In the unit dataset service add the save method
- [x] In the unit dataset store add the save method
- [x] Add UnitDataSetAdd.vue in /structural/views/unitDataSet with this fields:
1. input text localId (required)
2. input v-select search dataStructure (required)
3. input v-select search statsitcalProgram (required)
4. input text Name (required)
5. input text multiline Description 
6. input text version 
7. input test multiline Version Rationale
8. input date selection Version Date
9. input type v-select (ADMINISTRATIVE_REGISTER, DATA_HARVEST, PRODUCT, QUESTIONNAIRE, STATISTICAL_REGISTER) Exchange Channel (required)
10. input v-select ( COLLECT, DISSEMINATE) Exchange Direction (required)
11. input date range select for Reporting Begin and Reporting End
12. input string Connection (required)
13. input string Filter Expression

**Comment by ReiPano** [comment]
![image](https://user-images.githubusercontent.com/23282698/167306668-36afc7bf-f43a-4e70-998e-dbab3db8c35a.png)
![image](https://user-images.githubusercontent.com/23282698/167306684-2d94e04d-252c-416f-8e45-b88b15a26ff4.png)

**Comment by ReiPano** [comment]
Even when the values are provided for the "exchangeChannel" and "exchangeDirection", the server throws an error stating that these values can not be empty
