### ISSUE TITLE
Update Unit Dataset

### ISSUE THREAD

**Issue by florianika** [parstat/iais-frontend#113]
- [x] Add the update function in the service
- [x] Add the update function in the store
- [x] Create the UnitDataSetEdit.vue in views with the same fields as Add view, disabled fields:
1. LocalId
2. Statistical Program
3. Structure

**Comment by ReiPano** [comment]
![Screenshot 2022-05-08 at 7 33 37 PM](https://user-images.githubusercontent.com/23282698/167308299-6c71dc05-1376-41f5-886f-f37ccb411129.png)
![image](https://user-images.githubusercontent.com/23282698/167308309-7f969d76-1052-40c4-ae44-78bf0aaf2dfa.png)

**Comment by ReiPano** [comment]
When editing a unit data set the server will throw an error about the **Exchange Direction** being empty, even though it is present in the request.

**Comment by florianika** [comment]
@ReiPano I have fixed it.
