### ISSUE TITLE
Create Data Structure

### ISSUE THREAD

**Issue by florianika** [parstat/iais-frontend#115]
- [x] in the dataStructure.service create the save method
- [x] in the dataStructure store create the save method
- [x] Create the DataStructureAdd.vue view with three tabs: 
1. Basic 
    input type text LocalId (required)
    input type text Name (required)
    input type multiline Description
    input type text version
    input type date version Date
    input type text version Rationale
    button next (will create the datastructure and send to edit mode in tab 2: records)
2. Records (disabled)
4. Components (disabled)

**Comment by florianika** [comment]
@ReiPano: In the console I see some errors about handleBasic function but I suppose this will be fixed when finalizing edit data structure, right?

**Comment by ReiPano** [comment]
@florianika Yes, I will handle this when implementing the edit part
