### ISSUE TITLE
Variable add

### ISSUE THREAD

**Issue by florianika** [parstat/iais-frontend#57]
- [x] In the variable service add/check the save method 
- [x] In the variable store add/check the save method
- [x] Add/update VariableAdd.vue that should be a tabbed view with two tabs

1. Basic
    Fields: LocalId (required), Name (required), Description, Definition, Version.
    Next button that should save the variable and redirect in VariableEdit.vue in the second tab.
2. Representations (disabled)

**Comment by ReiPano** [comment]
When saving the data, an error is returned from the backend saying: 'Measures Id' must not be empty.
