### ISSUE TITLE
Unit Type add

### ISSUE THREAD

**Issue by florianika** [parstat/iais-frontend#63]
Steps needed to add a unit type:

- [x] Define save function in unitType.service.js in /services/structural/
- [x] Define a save method (function) in the store
- [x] Create the "add view" (.vue) in /views/metadata/structurla/unitType
- [x] The view should be mapped in /router/index.js

For the documentation of the api method to call in the service check: 
http://iais.francecentral.cloudapp.azure.com:8080/api/v1/structural/index.html (ClosedUnitTypes )

**Comment by florianika** [comment]
@ReiPano Please make the definition not mandatory.

**Comment by ReiPano** [comment]
@florianika Change was done and pushed. Should I also change the position of the filed? Since this field is no longer required and the field below (local id) is, should I switch their places?

**Comment by florianika** [comment]
@ReiPano You can put localId field to be the first one. I will anyway consider the task as finished.
