### ISSUE TITLE
Edit a unit type

### ISSUE THREAD

**Issue by florianika** [parstat/iais-frontend#65]
Steps needed to edit a unit type:

- [x] Define update function in unitType.service.js in /services/structural/
- [x] Define a update method (function) in the store
- [x] Create the "edit view" (.vue) in /views/metadata/structurla/unitType
- [x] The view should be mapped in /router/index.js

For the documentation of the api method to call in the service check: 
http://iais.francecentral.cloudapp.azure.com:8080/api/v1/structural/index.html (ClosedUnitTypes )

**Comment by ReiPano** [comment]
@florianika Should I add a form field for the version?

**Comment by florianika** [comment]
@ReiPano No for now it is not necessary.
