### ISSUE TITLE
Create CodeList

### ISSUE THREAD

**Issue by florianika** [parstat/iais-frontend#74]
- [x] Create Codelist view should be a tabbed view with two tabs:
1. Basic, containing this fields: Local Id required, Name required, Description, version, version date, version rationale. The tab should contain a next button, that saves the basics of codelist and redirects to CodeListEdit view, in the second tab.
2.  Code Items, desabled
- [x] Create the required save method in the service
- [x] Create the required method in the store.
Example to follow (https://github.com/parstat/iais-frontend/blob/vue3/src/views/metadata/referential/processDocumentation/ProcessDocumentationAdd.vue)

**Comment by ReiPano** [comment]
This part is deployed and tested successfully.
