### ISSUE TITLE
Update Codelist

### ISSUE THREAD

**Issue by florianika** [parstat/iais-frontend#75]
- [x] Edit Codelist view should be a tabbed view with two tabs:
1. Basic, containing this fields: Local Id required, Name required, Description, version, version date, version rationale. The tab should contain a next button, that saves the basics of codelist using the update method, and moves to the next tab
2.  Code Items containing this fields:  string code required,  string descripiton, v-select to search for label and a button "add" that will add the codeitem into the codelist and show it in a table below. Also should be visible a link "+ Add Label " to allow users to add the label if they don't find it. This should open a modal.
- [x] Create the required save method in the service
- [x] Create the required addCodeItem method in the service
- [x] Create the required save method in the store.
- [x] Create the required addCodeItem method in the store.

**Comment by ReiPano** [comment]
The function in the backend which handles the update is missing. Currently I can only create a new CodeList, Delete a CodeList, Add a CodeItem to a CodeList and Remove a CodeItem from a CodeList.
