### ISSUE TITLE
Add CodeItem to CodeList

### ISSUE THREAD

**Issue by florianika** [parstat/iais-frontend#76]

**Comment by ReiPano** [comment]
The form to add a CodeItem is added in the second tab of the CodeList edit. However, when testing this I got a 500 error without any explanation. The payload is shown in the screenshot attached here.
![Screenshot 2022-04-02 at 4 58 39 PM](https://user-images.githubusercontent.com/23282698/161389085-7acb74ad-0cc4-4aa5-b547-60d0d29409dc.png)
